resolver 10.230.238.22 10.236.238.22 ipv4=on ipv6=off valid=30s;
charset utf-8;
autoindex off;
server_tokens off;
more_clear_headers 'Server';
more_clear_headers 'X-Powered-By';

ssl_protocols TLSv1.2 TLSv1.3;
ssl_dhparam /usr/nginx/ssl/dhparam.pem;
ssl_session_tickets off;

keepalive_timeout 10s;
send_timeout 20s;

client_body_timeout 45s;
client_header_timeout 45s;
client_max_body_size 1m;
large_client_header_buffers 4 8k;
server_names_hash_bucket_size 256;
variables_hash_max_size 4096;
server_names_hash_max_size 2048;
variables_hash_bucket_size 512;

add_header X-Content-Type-Options "nosniff" always;
add_header X-XSS-Protection '1; mode=block';
add_header Strict-Transport-Security 'Strict-Transport-Security: max-age=31536000; includeSubDomains; preload';

scgi_temp_path         /usr/nginx/scgi_temp;
uwsgi_temp_path        /usr/nginx/uwsgi_temp;
fastcgi_temp_path      /usr/nginx/fastcgi_temp;
proxy_temp_path        /usr/nginx/proxy_temp_path;
client_body_temp_path  /usr/nginx/client_temp;

access_log /web_log/access.log;
error_log /web_log/error.log info;
error_page 403 404 500 502 503 504 /gt-error-page.html;